project:
  type: website
  output-dir: _site
  resources: 
    - "*.pdf"
  preview:
    port: 4200
    browser: false
website:
  title: ""
  site-url: http://localhost:4200/
  favicon: "logo.png"
  google-analytics: "G-5ZQX02R26E"
  open-graph: true
  navbar:
    # background:  #"transparent"
    pinned: false
    search: true
    logo: logo.png
    left:
      - text: "{{< fa house >}} Home"
        file: index.qmd  
      - text: "{{< fa book-open-reader >}} Data Science Notes"
        file: Data_Science_Notes/index.qmd
      - text: "{{< fa user-ninja >}} Paper Study"
        file: Paper_Study/index.qmd    
      - text: "{{< fa file-powerpoint >}} Data Science Projects"
        file: Data_Science_Projects/index.qmd           
      - href: about.qmd
        text: "{{< fa address-card >}} About"                         
    right:             
      - icon: github
        href: https://github.com/abhiyantaabhishek
      - icon: linkedin
        href: https://www.linkedin.com/in/abhishek-kumar-dubey-585a86179/
  sidebar:  
    - id: Paper_Study
      collapse-level: 1
      contents:
        - auto: "Paper_Study/"
      background: "#CBE4FA"  # corr "#CBE4FA" 
    - id: Data_Science_Notes
      collapse-level: 1
      contents:
        - auto: "Data_Science_Notes/"  
      # background: transparent
    - id: Data_Science_Projects
      collapse-level: 1
      contents:
        - auto: "Data_Science_Projects/"    
      # background: transparent                      
       
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Abhishek Kumar Dubey" 
    right: 
      - icon: github
        href: https://github.com/abhiyantaabhishek
      - icon: linkedin
        href: https://www.linkedin.com/in/abhishek-kumar-dubey-585a86179/
    background: light
  comments:
    giscus:
      repo: abhiyantaabhishek/IITH-Data-Science
      category: Announcements
format:
  html: 
    theme: cerulean
    # theme: 
    #   light: minty
    #   dark: slate    
    css: styles.css
    html-math-method: katex
    highlight-style: tango
    fig-align: center
    fig-responsive: true
    # page-layout: full
    grid:
      # sidebar-width: 200px
      body-width: 1000px
      # margin-width: 200px
    



