project:
  type: website
  output-dir: docs

website:
  title: "IITH-Data-Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/abhiyantaabhishek
      - icon: linkedin
        href: https://www.linkedin.com/in/abhishek-kumar-dubey-585a86179/
format:
  html:
    theme: cosmo
    css: styles.css



