project:
  type: website
  output-dir: _site
  resources: 
    - "*.pdf"
  preview:
    port: 4200
    browser: false
website:
  title: "IITH-Data-Science"
  favicon: "logo.png"
  google-analytics: "G-5ZQX02R26E"
  open-graph: true
  navbar:
    pinned: true
    search: true
    left:
      - text: "{{< fa house >}} Home"
        file: index.qmd  
      - text: "{{< fa book-open-reader >}} Data Science Tutorial"
        file: Data_Science_Tutorial/index.qmd
      - text: "{{< fa user-ninja >}} Data Science Hacks"
        file: Data_Science_Hacks/index.qmd     
      - href: about.qmd
        text: "{{< fa address-card >}} About"                         
    right:             
      - icon: github
        href: https://github.com/abhiyantaabhishek
      - icon: linkedin
        href: https://www.linkedin.com/in/abhishek-kumar-dubey-585a86179/
  sidebar:  
    - id: Data_science_hacks
      collapse-level: 1
      contents:
        - auto: "Data_Science_Hacks/"
    - id: Data_science_Tutorial
      collapse-level: 1
      contents:
        - auto: "Data_Science_Tutorial/"                   
       
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Abhishek Kumar Dubey" 
    right: 
      - icon: github
        href: https://github.com/abhiyantaabhishek
      - icon: linkedin
        href: https://www.linkedin.com/in/abhishek-kumar-dubey-585a86179/
    background: light
  comments:
    giscus:
      repo: abhiyantaabhishek/IITH-Data-Science
      category: Announcements
format:
  html: 
    theme: cosmo
    # theme: 
    #   light: minty
    #   dark: slate    
    css: styles.css
    html-math-method: katex
    highlight-style: tango
    fig-align: center
    fig-responsive: true
    number-sections: true


